### ISSUE TITLE
Is there any requirement.txt that i need to do pip install.

### ISSUE THREAD

**Issue by golf-x** [hartwork/xiangqi-setup#125]
I would like to contribute to this codebase and trying to understand this.
I am quite new to python as well.
do i need to pip install or somethings ? i do not see any requirement.txt here

**Comment by hartwork** [comment]
> I would like to contribute to this codebase

Let's discuss potential contributions at least on a high lever first please, so that we don't end up in a situation where you spent hours on a pull request to then find out that it's taking the project in a direction that I won't be able to support. Let's talk tzo avoid future frustration on either side. Issue #126 is a good move in that direction, just seen.

> and trying to understand this. I am quite new to python as well. do i need to pip install or somethings ? i do not see any requirement.txt here

There is no such file here, true. I currently recommend `pip install -e .[tests]` which is what the CI is doing at…https://github.com/hartwork/xiangqi-setup/blob/a2a2be8d22d4225b519fcbbaa0c39d18df46448a/.github/workflows/smoke_test.yml#L31-L35

It effectively combines the runtime dependencies from…
https://github.com/hartwork/xiangqi-setup/blob/a2a2be8d22d4225b519fcbbaa0c39d18df46448a/setup.py#L52-L60
…with the test dependencies from:
https://github.com/hartwork/xiangqi-setup/blob/a2a2be8d22d4225b519fcbbaa0c39d18df46448a/setup.py#L11-L18

Does that work to get you started?

**Comment by golf-x** [comment]
I ran

```shell
pip install -e .[tests]
```

I got

zsh: no matches found: .[tests]

**Comment by hartwork** [comment]
@golf-x I see, I am not familiar with zsh (but Bash). With zsh it seems to need additional quoting like this:

```console
# pip install -e '.[tests]'
```
Does that work for you?

**Comment by golf-x** [comment]
Yes, that's work.

Can we create something like CONTRIBUTING.md? 
So we can consolidate this kind of knowledge to future contributors?

**Comment by hartwork** [comment]
> Can we create something like CONTRIBUTING.md? So we can consolidate this kind of knowledge to future contributors?

@golf-x done in #129 just now.

Closing this ticket as "question answered".
